version: "3.9"

services:
  # Uncomment if need use ollama in docker with depends_on and columes
  # ollama:
  #   image: ollama/ollama:0.11.8
  #   container_name: ollama
  #   ports:
  #     - "11434:11434"
  #   volumes:
  #     - ollama_data:/root/.ollama
  #   entrypoint: ["ollama", "serve"]

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    env_file:
      - server/.env
    depends_on:
      # - ollama
      - postgres

  postgres:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  # ollama_data:
  postgres_data:
